name: antinvestor_api_trustage
description: Dart client library for Ant Investor Trustage Service
version: 0.1.0
repository: https://github.com/antinvestor/service-trustage
homepage: https://github.com/antinvestor/service-trustage
issue_tracker: https://github.com/antinvestor/service-trustage/issues

environment:
  sdk: ^3.3.0

dependencies:
  protobuf: ^4.2.0
  connectrpc: ^1.0.0
  fixnum: ^1.1.0
  antinvestor_api_common: ^1.52.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

topics:
  - grpc
  - protobuf
  - api-client
  - trustage
