// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Union2KassistantOrKuser struct {
	variant string

	variant_Kuser *string

	variant_Kassistant *string
}

func (u *Union2KassistantOrKuser) Decode(holder *cffi.CFFIValueUnionVariant, typeMap baml.TypeMap) {
	valueHolder := holder.Value
	variantName := holder.ValueOptionName
	switch variantName {
	case "string_user":
		u.variant = "Kuser"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kuser = &value
	case "string_assistant":
		u.variant = "Kassistant"
		value := baml.Decode(valueHolder).Interface().(string)
		u.variant_Kassistant = &value

	default:
		panic(fmt.Sprintf("invalid union variant: %s", variantName))
	}
}

func (u Union2KassistantOrKuser) Encode() (*cffi.HostValue, error) {
	switch u.variant {

	case "Kuser":
		return baml.EncodeValue(*u.variant_Kuser)

	case "Kassistant":
		return baml.EncodeValue(*u.variant_Kassistant)

	case "":
		return nil, fmt.Errorf("invalid union variant: [unset]")
	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u Union2KassistantOrKuser) BamlTypeName() string {
	return "Union2KassistantOrKuser"
}

func (u Union2KassistantOrKuser) MarshalJSON() ([]byte, error) {
	switch u.variant {

	case "Kuser":
		return json.Marshal(u.variant_Kuser)

	case "Kassistant":
		return json.Marshal(u.variant_Kassistant)

	}

	return nil, fmt.Errorf("invalid union variant: %s", u.variant)
}

func (u *Union2KassistantOrKuser) UnmarshalJSON(data []byte) error {
	var err error

	err = json.Unmarshal(data, &u.variant_Kuser)
	if err == nil {
		u.variant = "Kuser"
		return nil
	} else {
		u.variant_Kuser = nil
	}

	err = json.Unmarshal(data, &u.variant_Kassistant)
	if err == nil {
		u.variant = "Kassistant"
		return nil
	} else {
		u.variant_Kassistant = nil
	}

	return fmt.Errorf("invalid union variant: %s", string(data))
}

func Union2KassistantOrKuser__NewKuser() Union2KassistantOrKuser {

	var v string = "user"

	return Union2KassistantOrKuser{
		variant:       "Kuser",
		variant_Kuser: &v,
	}
}

func (u *Union2KassistantOrKuser) SetKuser() {

	var v string = "user"

	u.variant = "Kuser"
	u.variant_Kuser = &v

	u.variant_Kassistant = nil

}

func (u *Union2KassistantOrKuser) IsKuser() bool {
	return u.variant == "Kuser"
}

func (u *Union2KassistantOrKuser) AsKuser() *string {
	if u.variant != "Kuser" {
		return nil
	}
	return u.variant_Kuser
}

func Union2KassistantOrKuser__NewKassistant() Union2KassistantOrKuser {

	var v string = "assistant"

	return Union2KassistantOrKuser{
		variant:            "Kassistant",
		variant_Kassistant: &v,
	}
}

func (u *Union2KassistantOrKuser) SetKassistant() {

	var v string = "assistant"

	u.variant = "Kassistant"
	u.variant_Kassistant = &v

	u.variant_Kuser = nil

}

func (u *Union2KassistantOrKuser) IsKassistant() bool {
	return u.variant == "Kassistant"
}

func (u *Union2KassistantOrKuser) AsKassistant() *string {
	if u.variant != "Kassistant" {
		return nil
	}
	return u.variant_Kassistant
}
