// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

var file_map = map[string]string{

	"chat.baml":       "class Message {\n  role \"user\" | \"assistant\"\n  content string\n}\n\n// Default client — overridden at runtime via ClientRegistry.\nclient<llm> DefaultLLM {\n  provider \"openai\"\n  options {\n    model \"gpt-4o\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nfunction Chat(messages: Message[], system_prompt: string) -> string {\n  client DefaultLLM\n  prompt #\"\n    {{ _.role(\"system\") }}\n    {{ system_prompt }}\n\n    {{ ctx.output_format }}\n\n    {% for m in messages %}\n    {{ _.role(m.role) }}\n    {{ m.content }}\n    {% endfor %}\n  \"#\n}\n",
	"generators.baml": "generator target {\n  output_type \"go\"\n  output_dir \"../\"\n  version \"0.217.0\"\n  client_package_name \"github.com/antinvestor/service-trustage\"\n  on_generate \"gofmt -w . && goimports -w . && go mod tidy\"\n}\n",
}

func getBamlFiles() map[string]string {
	return file_map
}
