// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/antinvestor/service-trustage/baml_client/stream_types"
	"github.com/antinvestor/service-trustage/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.Message":        reflect.TypeOf(types.Message{}),
	"STREAM_TYPES.Message": reflect.TypeOf(stream_types.Message{}),

	"TYPES.string_assistant__string_user": reflect.TypeOf(types.Union2KassistantOrKuser{}),
}
